name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Build Docker image
      run: |
        docker build -t gcr.io/blueguard-healthpay/myapp .

    - name: Push Docker image
      env:
        GCP_PROJECT_KEY: ${{ secrets.GCP_PROJECT_KEY }}
      run: |
        echo ${{ secrets.GCP_PROJECT_KEY }} | docker login -u _json_key --password-stdin https://gcr.io
        docker push gcr.io/blueguard-healthpay/myapp

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_PROJECT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy myapp --image gcr.io/blueguard-healthpay/myapp --platform managed --region us-central1
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_PROJECT_KEY }}

